### ISSUE TITLE
admin.sh delete inconsistency

### ISSUE THREAD

**Issue by tparker-usgs** [usgs/winston#24]
Reported:
I used this command to remove all rows associated with PGBF1 :
java -cp lib/winston.jar gov.usgs.winston.db.Admin --delete 'PGBF1$BDF$MI$--'

This also removes the database of the same name in the mysql database, so no PGBF1 channels exists in either the WWS nor mysql. 

I then tried to import a subset of data with this scnlc 'PGBF1$BDF$MI$--", but WWS throws this error back:

Importing channel: PGBF1$BDF$MI$--.
Converting 1 waves into TraceBufs.
Writing TraceBufs to database.
2016-02-16 12:25:08: (INFO) Connected to database.
2016-02-16 12:25:08: (INFO) Attempt to use nonexistent database: PGBF1$BDF$MI
Done.

**Comment by dlnorgaard** [comment]
I encountered something similar with --delete FG10$A%$GI$--.  I wanted to delete all FG10 with channels that began with A, but it ended up removing all of FG10.

**Comment by tparker-usgs** [comment]
That's not good. --delete is intended to delete a single channel, it should escape any wildcards that are passed to it. --deletex was contributed to allow wildcard matching.

Thanks for reporting this.

**Comment by tparker-usgs** [comment]
I'm not able to duplicate either of these issues. Both --delete and --deletex work as expected in my tests. Note that --delete does not accept wild cards. It is only able to delete a single channel and throws the correct error when given a wildcard in my tests.

If you are able to duplicate this problem, please reopen the ticket. Include any OS, Java, MySQL details that may help me duplicate this problem.
