### ISSUE TITLE
two location codes, null iid ImportHypoinverse

### ISSUE THREAD

**Issue by roadworrier** [usgs/winston#35]
561	33	M005$HLE$MM$01	547619740.680007	551298241.68			1e+300	1e+300
	824	null M005$HLE$MM	551298242.68	551387697.680001			1e+300	1e+300

I run the gov.usgs.winston.in.metadata.ImportHypoinverse and only the 01 channel is updated with a link to the instruments table. I needed to manually go in and edit the iid for the same station with no location code, so I would have the option to have that same station appear on the Swarm map.

**Comment by tparker-usgs** [comment]
The hypoinverse input appears to be malformed. That will cause trouble for the importer. If this is just an artifact of the issue input box, please email your hypoinverse file to tparker@usgs.gov and I'll take a look.
