### ISSUE TITLE
Getmenu fails, but Swarm works.

### ISSUE THREAD

**Issue by roadworrier** [usgs/winston#61]
The command-line Earthworm tool getmenu fails, as does an ObsPy connect, but Swarm works as does pointing a web browser at :16022

This is after some Winston admin tool work was done which may or may not be related (I don't know exactly what was done, it wasn't done by me). The error is:

java.lang.ArrayIndexOutOfBoundsException: 2
        at gov.usgs.winston.db.WaveServerEmulator.getWaveServerMenu(WaveServerEmulator.java:106)
        at gov.usgs.winston.server.cmd.MenuCommand.doCommand(MenuCommand.java:33)
        at gov.usgs.net.CommandHandler.run(CommandHandler.java:109)
2018-01-05 20:54:22: (SEVERE) Unhandled exception in main CommandHandler loop.
 ^------- Exception: java.lang.ArrayIndexOutOfBoundsException/2
  ^---- Stack Trace: gov.usgs.winston.db.WaveServerEmulator.getWaveServerMenu/WaveServerEmulator.java:106
  ^---- Stack Trace: gov.usgs.winston.server.cmd.MenuCommand.doCommand/MenuCommand.java:33
  ^---- Stack Trace: gov.usgs.net.CommandHandler.run/CommandHandler.java:109

The version was 1.2.8, but updating to 1.2.12 doesn't seem to have made a difference.

The code column in WWS_ROOT.channels seems to match the WWS_ databasename every time, so I'm ruling that out as the issue.

Java is 
$ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Any suggestions on how I can debug further on my end?

- Stefan at ISTI

**Comment by tparker-usgs** [comment]
The exception sorta looks like the winston database contains channels without a network code. Do you see any other oddities that might suggest a problem with SCNLs in the database?

Winston expects at least a s$c$n in the channels table.

**Comment by roadworrier** [comment]
Ah, indeed! Thanks Tom for catching that. I hadn't noticed that was the case with some of the channels. I see a number of channels that look like WWS_UNKN$XYZ$
(Where XYZ is replaced by 20 unfamiliar channel codes which I presume must be digitizer state of health channels.) I wonder where the UNKN came from, or how these channels arrived. Can you think of anything in the Winston Tools that would have resulted in this? Since I wasn't the one doing the "clean up" I don't know exactly what commands were run. I do know wildcards were used at least some of the time. (These same channel codes do show up a second time under WWS_real_station_name$code$network_code)

If I drop these network code-less lines from the channel tables and delete the data files, that should be as safe as deleting them using the admin tool, yes?

Thanks again!

**Comment by roadworrier** [comment]
OK, this appears to have nothing to do with Winston Tools. In this Earthworm system, there really are channels being imported with ImportEW with no network code. As soon as those get into the database, "getmenu" fails. Clear them out, "getmenu" is happy. Perhaps Import EW should reject them by default, since WWS can't send back a menu of networkcodeless channels? (Or alternately maybe ImportEW could have an option to let people import networkcodeless channels, which is turned off by default, so that only unusual power users would be allowed to corrupt their database with these channels? Just in case anyone wants this behavior...) Thanks. I'm set anyway.

**Comment by roadworrier** [comment]
(These statistical channels were being introduced by a Q330S. Once these channels were deleted with Willard, we haven't see this issue with Winston. )
