### ISSUE TITLE
in tracebuf to wave

### ISSUE THREAD

**Issue by slisowski** [usgs/winston#62]
We've got Winston loaded into Earthworm's startstop with --noinput set, but we're seeing a message "in tracebuf to wave" appearing on the Startstop screen continuously. If we remove Winston from startstop this message goes away. 
I don't think the message is in the export_generic in Earthworm that talks to Winston's ImportEW as I've been unable to grep for any piece of this string in Earthworm, and I haven't seen this before. However, I also tried to grep in the Winston java source code for this string without luck. (The message doesn't appear in Winston logs, nor in Earthworm logs.)
Have you seen this message before? Any ideas on how to squelch it?

**Comment by tparker-usgs** [comment]
That sounds like debugging output that escaped into general release. However, I can't find that string in the current codebase. Which version of Winston are you running?

**Comment by slisowski** [comment]
Looks like winston-1.2.12.zip was the source for this installation.

**Comment by slisowski** [comment]
turns out this was an older version of Winston; the 1.2.12.zip was on this system, but wasn't the software which actually was installed... system has since been upgraded and I haven't heard of this issue reappearing.
