### ISSUE TITLE
hypoinverse loader into WINSTON doesn't know defaults of hypoinverse station file

### ISSUE THREAD

**Issue by seismopaul** [usgs/winston#65]
The hypoinverse station loader portion of Winston fails to follow the defaults of the station file. If there is no latitude char, the default is Northern Hemisphere and if there is no longitude char, the default is Western Hemisphere (negative longitudes).  When I just loaded some data with a valid hypoinverse file (no lat or lon chars since all was in Western Hemisphere and northern latitudes), it loaded the data but gave the longitudes positive values. This placed all of the stations in China.....

**Comment by tparker-usgs** [comment]
Thanks! This will be fixed in 1.3.5, to be released this week.
