### ISSUE TITLE
WWS 1.2.12 crashes with java NullPointerException error

### ISSUE THREAD

**Issue by seismopaul** [usgs/winston#68]
Erol Kalkan noticed with WWS version 1.2.12 the following error in the WWS log file below. I am just opening a github ticket to record it in case others have seen this. 

> 2018-09-14 18:59:25: (INFO) 127.0.0.1/slow db query (2570.27 ms) GETSCNLRAW 8045$HNE$NP$15 5.9014944E8 -> 5.9014956E8 (120) 
> 2018-09-14 18:59:29: (SEVERE) Could not get raw wave.
>  ^------- Exception: java.lang.NullPointerException/null
>   ^---- Stack Trace: java.io.ByteArrayInputStream.<init>/null:???
>   ^---- Stack Trace: gov.usgs.earthworm.message.TraceBuf.<init>/TraceBuf.java:98
>   ^---- Stack Trace: gov.usgs.winston.db.WaveServerEmulator.getWaveServerRaw/WaveServerEmulator.java:195
>   ^---- Stack Trace: gov.usgs.winston.server.cmd.GetSCNLRawCommand.doCommand/GetSCNLRawCommand.java:66
>   ^---- Stack Trace: gov.usgs.net.CommandHandler.run/CommandHandler.java:109
> 2018-09-14 18:59:29: (INFO) 127.0.0.1/slow db query (3859.82 ms) GETSCNLRAW 8045$HNE$NP$15 5.901528E8 -> 5.9015292E8 (120) 
> 2018-09-14 19:00:03: (SEVERE) Could not get raw wave.
>  ^------- Exception: java.lang.NullPointerException/null

**Comment by tparker-usgs** [comment]
I haven't seen this one before. If it happens again, check the MySQL logs for any hints.

A lot changed between WWS 1.2 and 1.3. I'm going to close this for now, but if the problem arises again, especially in 1.3, please re-open the ticket with any additional details.
