### ISSUE TITLE
Winston cannot create its database tables when using utf8mb4 character set

### ISSUE THREAD

**Issue by XavierBeguin** [usgs/winston#69]
I got the following error when first starting ImportEW on a new installation:
```
...
(INFO) Created new Winston database: W
(SEVERE) Could not create tables in WWS database.  Are permissions set properly?
  ^------- Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException/Specified key was too long; max key length is 1000 bytes
  ...
```
MySQL/MariaDB uses the largest possible size of a character in the current character set to calculate a key size, and will refuse to create a key that is potentially larger that the max key length.

Depending on the configured character set, a character could be encoded using 1 to 4 bytes (this also depends on [the unicode charset](https://mariadb.com/kb/en/library/unicode/) in use). As the key length limit cannot be changed when using the Winston-recommended MyISAM engine, this means that keys should not be larger than 1000/4=250 bytes to account for the worst case.

In particular, you will meet this problem when using [MariaDB on Debian](https://mariadb.com/kb/en/library/differences-in-mariadb-in-debian-and-ubuntu/), as it uses `utf8mb4` as default character set which uses up to 4 bytes for a character, while `utf8` (aka `utf8mb3`) doesn't use more than 3 bytes, which won't make any key in the Winston database larger than the limit.

From a quick glance at the table schemas defined by Winston, the size of the columns used in keys could easily be limited, as it seems to only concern the following columns (I did not test if this was enough, though):

- `W_ROOT.channelmetadata.name`: if my understanding is good, as it is combined with the `sid` column for the primary key, it should not be more than 250-11=239 characters, and therefore be a VARCHAR(239) instead of VARCHAR(255);

- `W_ROOT.instruments.name`: it should be VARCHAR(250) instead of VARCHAR(255).

In the meantime, there are possible workarounds if your server uses `utf8mb4` as a default server character set:

- change the default character set to `utf8` (for example) on your MySQL or MariaDB server. With MariaDB on Debian, this can be achieved by creating a file `/etc/mysql/mariadb.conf.d/90-local.cnf` with the following content, and restarting the MariaDB server:
```ini
[mysqld]
character-set-server  = utf8
collation-server      = utf8_general_ci
```

- a better option is to hijack the `tableEngine` option in `Winston.config` to specify a character set to use when creating tables:
```
winston.tableEngine=MyISAM CHARSET=utf8
```

**Comment by tparker-usgs** [comment]
Thanks for the detailed report. This should be fixed in version 1.3.4 to be released this week.
