### ISSUE TITLE
Return height/elevation in metadata

### ISSUE THREAD

**Issue by dlnorgaard** [usgs/winston#71]
There is a Swarm request to display height info (https://github.com/usgs/swarm/issues/222) but Winston is not returning this info in the metadata.  I think it is just a matter of adding it to Channel.toMetadataString(), but it's unclear to me how to synchronize changes in the server with the client.  Channel.parse() method would also need to be updated I think, but unless the server and the client are both on the same version there might be problems since the returned string might be different from what is expected.  Maybe one way is to check the length of ss in parse.

**Comment by tparker-usgs** [comment]
I don't think there's a way to add height to the GETCHANNELS command without breaking existing clients. You spotted the problem, an exact match on argument count in Channel.parse(). That's no good.

However, instrument height is returned by the GETMETADATA command. I'm closing this for now. If GETMETADATA won't work for you or if you have an idea for accommodating height in GETCHANNELS, re-open the ticket.

```
java -jar target/wwsclient-1.3.6.jar --server pubavo1.wr.usgs.gov  --command "GETMETADATA 1 INSTRUMENT"
2019-04-02 02:33:24  INFO - Received 1024 bytes.
1 432
name=ACH,description=,longitude=-155.3281,latitude=58.21,height=960.0,timezone=null,
name=ADAG,description=,longitude=-176.6037,latitude=51.9791,height=286.0,timezone=null,
name=AHB,description=,longitude=-165.8177,latitude=54.1144,height=447.0,timezone=null,
name=AJAX,description=,longitude=-158.2238,latitude=56.8887,height=967.0,timezone=null,
name=AK1,description=,longitude=-165.772,latitude=54.135,height=12.0,timezone=null,
name=AK2,description=,longitude=-165.7803,latitude=54.1233,height=90.0,timezone=null,
name=AK3,description=,longitude=-165.772,latitude=54.135,height=12.0,timezone=null,
name=AK4,description=,longitude=-165.7337,latitude=54.1091,height=135.0,timezone=null,
name=AK5,description=,longitude=-165.867,latitude=54.15434,height=225.0,timezone=null,
name=AKBB,description=,longitude=-165.9338,latitude=54.0975,height=310.0,timezone=null,
name=AKGG,description=,longitude=-165.9936,latitude=54.1979,height=326.0,timezone=null,

```
