### ISSUE TITLE
admin.sh --list does not return to shell

### ISSUE THREAD

**Issue by jpesicek** [usgs/winston#75]
new version does not return to shell in 1.3.3, but old 1.2 version does.  I have to CRTL+C it

**Comment by tparker-usgs** [comment]
I'm not able to replicate this. Perhaps the problem is specific to certain arguments? 
If you're still experiencing this problem, please reopen the ticket and add the exact command line you're using.

**Comment by jpesicek** [comment]
I reconfirmed, exact command is:

./Admin.sh --list
./Admin.sh --list times
