### ISSUE TITLE
Winston logging filenames are ignored in 1.3.X

### ISSUE THREAD

**Issue by seismopaul** [usgs/winston#77]
The previous properties in WWS and ImportEW that specified the log file name don't seem to be used. We attempted to set the log via the properties, but we noticed that the default name was still used despite being echoed back in the log. Here is how we set the log names, which worked in 1.2.12:

in WWS.config we have:

log.name=../log/WWS.log

in ImportEW.config we have:

import.log.name=../log/ImportEW.log

and in ImportEW2.config we have:

import.log.name=../log/ImportEW2.log

Yet in each case the log is the default name and written to the run directory.

**Comment by tparker-usgs** [comment]
The log config options are no longer used. Looking to the config for logging information prevents logging startup errors. I'll add command line args to specify the logging location.
