### ISSUE TITLE
Initial client character set can be forced via the 'characterEncoding' property.

### ISSUE THREAD

**Issue by stefanisti** [usgs/winston#81]
Installed MySQL 8.0.16 on MaxOSX, and I get the error "Initial client character set can be forced via the 'characterEncoding' property." when ImportEW tries to connect to the database.

mysql -u winstonuser -p

connects just fine, and I can create a new database W_foo so it isn't a credentials or permissions issue.

**Comment by tparker-usgs** [comment]
Other than the message about the characterEncoding property, do things seem to work okay?

**Comment by stefanisti** [comment]
Sorry my initial ticket wasn't more clear. No, it doesn't work; ImportEW doesn't create any databases, doesn't save any data. Let me know if you need more information; I can try and reproduce on my own machine.

**Comment by tparker-usgs** [comment]
I suspect this is a duplicate of #69. A fix for that issue will be in 1.3.4, please reopen this ticket if you experience the same issue in that version.

The problem in #69 also affects the instrument table which might bring everything to a halt.
